# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main, dev ]

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Count Lines of Code (cloc)
      uses: djdefi/cloc-action@650d8d41912cfc74019c6906f69e7ba2e4de6615

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --info
    - name: Package build output
      uses: actions/upload-artifact@v3
      with:
        name: adif2csv
        path: build/distributions/*.zip 
